### ISSUE TITLE
Create 'interim' page for PlanetFour.org

### ISSUE THREAD

**Issue by trouille** [zooniverse/retirement#10]
For April 30th Ouroborous shutdown date, create 'interim' page for PlanetFour.org, following the template/approach as for https://whaling.oldweather.org. 

Differences: 
- Remove the 'Old Weather' button. 
- The 'Publications' button should link to https://www.planetfour.org/#/results (not zooniverse.org/publications)
- Add a 'Blog' button that links to http://blog.planetfour.org/

https://talk.planetfour.org/ will persist as is for now.

**Comment by trouille** [comment]
PlanetFour.org will be the URL for this 'interim' page. Note: this interim page likely to be needed until August/September when the PFE project they're building will be ready for beta review.

**Comment by trouille** [comment]
Key is that https://www.planetfour.org/#/results and https://www.planetfour.org/#/authors remain real URLs w/ same current content (since Planet Four publications reference these URLs and they reference each other). 

In Slack, Adam noted that "It’s not quite so simple as adding it to Nginx since it’s using a url fragment identifier for the url (ie the hash sign). The archive page itself will need to handle that client side."

**Comment by trouille** [comment]
By Friday (4/26) I'll have the few sentences of copy and an image from the P4 team to put into this interim page.

**Comment by camallen** [comment]
> In Slack, Adam noted that "It’s not quite so simple as adding it to Nginx since it’s using a url fragment identifier for the url (ie the hash sign). The archive page itself will need to handle that client side."

is it possible to publish a static page that mirrors the current content on `https://www.planetfour.org/#/results` with a nginx rewrite rule or similar? is that better then running the JS code app forever?

**Comment by adammcmaster** [comment]
If we want to keep the URL the same, we can't do anything in Nginx to handle that. It needs to be done client side. This could be as simple as having the results on the index page with `<h2 id="/results">Results</h2>` as the heading.

**Comment by trouille** [comment]
@wgranger Image for planet four from Meg:
![P4_logo](https://user-images.githubusercontent.com/4975655/56922590-29298d00-6a8e-11e9-8da7-6600833c1187.jpg)

**Comment by trouille** [comment]
Text for planet four interim page from Meg:

Planet Four

Through Planet Four, Zooniverse volunteers mapped seasonal fans on the 
south polar region of Mars, providing new insights into the seasonal 
processes and weather active on the Red Planet.

This project is paused while we are working on a new version of Planet 
Four utilizing the Zooniverse’s latest web platform. Check back soon for 
updates.

In the meantime, please help map the exotic terrains of Mars' south pole 
with Planet Four: Terrains or help map polygonal ridges on Mars with 
Planet Four: Ridges.

(With Planet Four: Terrains linked to https://www.zooniverse.org/projects/mschwamb/planet-four-terrains and Planet Four: Rigdges linked to https://www.zooniverse.org/projects/mschwamb/planet-four-ridges).

**Comment by trouille** [comment]
In terms of buttons, please:

- Remove the 'Old Weather' button.
- The 'Publications' button should link to https://www.planetfour.org/#/results (not zooniverse.org/publications)
- Add a 'Blog' button that links to http://blog.planetfour.org/
- Add a 'Discussion Forum' button that links to https://talk.planetfour.org/

**Comment by trouille** [comment]
And note that within  https://www.planetfour.org/#/results is a link to https://www.planetfour.org/#/authors. 

Both of these links are noted in publications and so do need to persist as accessible URLs (not just for this interim page).
