### ISSUE TITLE
Create 'interim' page for DiskDetective.org

### ISSUE THREAD

**Issue by trouille** [zooniverse/retirement#11]
For April 30th Ouroborous shutdown date, create 'interim' page for DiskDetective.org, following the template/approach as for https://whaling.oldweather.org.

(It's an 'interim' page because Kuchner and co are in process of rebuilding on PFE, but won't be ready for beta till summer). 

I expect to have content (a few sentences of text and an image) from Kuchner by Friday noon. 

Note: https://talk.diskdetective.org/ should persist as is.

**Comment by trouille** [comment]
Note: I'm checking w/ Kuchner if any other URLs need to persist (e.g., https://www.diskdetective.org/#/authors). Will post here with update. 

Update: Yes, Kucyner does need https://www.diskdetective.org/#/authors to remain accessible.

**Comment by trouille** [comment]
@wgranger Marc provided the following text:

Planets like ours form in disks around stars. Citizen scientists used Disk Detective to find thousands of these disks, including new kinds of disks that had never been seen before, like the "Peter Pan Disk" illustrated here (credit: Jonathan Holden). We're working on a new version of Disk Detective that will be even more powerful.  In the meantime, please check out Backyard Worlds: Planet 9!

(With Backyard Worlds: Planet 9 linked to https://www.zooniverse.org/projects/marckuchner/backyard-worlds-planet-9).

**Comment by trouille** [comment]
Here's the image to use with it: 
https://drive.google.com/file/d/1RwC2WQFpkUeMOmX78Te2osQ76Ccbjdrf/view?usp=sharing

**Comment by trouille** [comment]
For the 'Old Weather' button from https://whaling.oldweather.org/#/, for this Disk Detective archive page, could you replace 'Old Weather' with 'Check out Backyard Worlds', with that button linking to https://www.zooniverse.org/projects/marckuchner/backyard-worlds-planet-9. Not necessary (since it's also in the text), but just if easy.

**Comment by wgranger** [comment]
If discdetective.org is being shut down, where should https://www.diskdetective.org/#/authors redirect to? Previously, we've redirected to a PFE instance of the project. However, if we need the current content as is from /#/authors then I'll have to create a new static page.

**Comment by trouille** [comment]
In this case, yes, you'll need to create a new static page w/ this info. Sorry.
