### ISSUE TITLE
Create 'interim' page for Chimp&See

### ISSUE THREAD

**Issue by trouille** [zooniverse/retirement#12]
For April 30th Ouroborous shutdown date, create 'interim' page for chimpandsee.org, following the template/approach as for https://whaling.oldweather.org.

Difference:

- Remove the 'Old Weather' button.

The chimp and see team has put a new PFE built project through beta, but need to make some updates and expect to launch that project in summer. So better to have the interim page while they're making those updates (to avoid confusion from their volunteers). Their PFE project is https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see (with one of the best usernames I've seen).

**Comment by trouille** [comment]
The text to replace the Whaling text is:

Annotations on Chimp&See will be back soon - we are still doing chimp matching on Talk so visit us there to watch videos or join in the conversation. 

And link the word 'there' to https://talk.chimpandsee.org/

And this means, as with all other Ouroboros projects we're retiring at the moment, that  https://talk.chimpandsee.org/ will persist.

**Comment by trouille** [comment]
The image to use is attached. 
![chimp](https://user-images.githubusercontent.com/4975655/56741080-c8b9e900-6737-11e9-9cd2-e81e30e76a09.png)

**Comment by trouille** [comment]
Also, please redirect  https://www.chimpandsee.org/#/about/authors to https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/about/team

**Comment by wgranger** [comment]
![Screen Shot 2019-04-25 at 9 49 04 AM](https://user-images.githubusercontent.com/14099077/56745124-682eaa00-673f-11e9-96b3-beb63414549f.png)

**Comment by wgranger** [comment]
I think this should cover everything. Opening a PR now. It takes about 30 minutes on the frontend side to make the changes seen above.

**Comment by trouille** [comment]
Just an FYI/ comment - I took a screencapture video for posterity of the chimp&see current site, and plan to do the same for all the others pre-retirement. I'll share w/ Becky to see where to store these videos for future access (it's useful for those of us who give talks and want to reference old projects).

**Comment by AnLand** [comment]
Maybe the "Return to classifying" button could be removed as well to avoid confusion? Temporally if it will be redirected later to the new project or entirely if old Chimp&See Talk will be archived as stand alone. Just an idea as the current solution is a bit circular.

**Comment by trouille** [comment]
Good catch. Yes, in the old Talk there's a 'return to classifying' button. We can't do anything about that button at the moment, but eventually when old Talk is turned into a static, read-only page, then we'll address that issue.

**Comment by trouille** [comment]
Important note -- please hold off on making this page public until April 30th or later. Planet Four team is sending a newsletter and posting a blog post w/ that as the switchover date.

**Comment by AnLand** [comment]
For Chimp&See this is already public and announced on social media (twitter, facebook, blogspot). So, no need to change it back. That's why I thought the "Return to classifying" button is confusing as there is no classifying until later after relaunch.
