### ISSUE TITLE
Edit Operation War Diary retirement page content

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/retirement#36]
Current text is missing any mention that the project is retired / complete.  Please updated text to the following:

"This Zooniverse project was built in collaboration with the Imperial War Museum and the National Archives. For 5 years volunteers transcribed and annotated World War I field notes from the Western Front.  The first phase of this project is now complete, and thank you to all those who participated."

**Comment by eatyourgreens** [comment]
There's a page where you can download the diary data as CSVs at http://wd3.herokuapp.com/public but it ~~seems to be down right now~~ is on a free Heroku plan so goes down every now and again.

**Comment by adammcmaster** [comment]
Similar to my comment on #38, we should only link to that if we can maintain it.

**Comment by eatyourgreens** [comment]
If we remove it, those data CSVs will still need to be made available from this page somewhere.

**Comment by lcjohnso** [comment]
I'll note that the data app worked for me (just needed time to spin-up the sleeping free instance on heroku), but that a flat data page with links to CSVs and external diaries would be easier from a maintenance perspective moving forward.

**Comment by wgranger** [comment]
There are 888 CSVs on that linked page, which is not at all a trivial number of CSVs to include on this page. I can easily create a link to the archive page above, but creating a flat data page will take much more work that should be held in a separate issue or possibly a separate repo altogether.

**Comment by lcjohnso** [comment]
@wgranger Agreed -- I'm OK with including the link the existing archive page, and updating if/when changes or a replacement page are created.

I'm of the same mind for all similar links on other pages, but what is the deploy process for these, in the context of "what needs to be done to edit these pages after initial creation/deploy"?  As simple as merging the PR in this repo, or also necessary to copy over page dir to separate hosted location manually?

**Comment by wgranger** [comment]
I think that depends on how we go about hosting the CSVs. This is just the first time something bigger like that has come up. I'd imagine we would make a change to the external link here and host that info somewhere else?
