### ISSUE TITLE
Create an archive page for Science Gossip

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/retirement#38]
Following Worm Watch Lab / Chimp & See template, please create a retirement page for the Science Gossip project.

Retirement Page Text:
"The Science Gossip project helped bring the work of nineteenth-century citizen scientists to light so that we can better understand the origins of our collective scientific undertaking today.  Participants tagged images from Victorian periodicals full of collaborative articles and discoveries in the fields of botany, geology, paleontology, microscopy, and more.  The project is now complete: nearly ten thousand volunteers produced more than half a million classifications.  This work helped inform research articles, including one published in the British Journal for the History of Science."

Link Buttons:
Standard -- Zooniverse and Zooniverse Publications
Link: "Blog" = https://sciencegossipblog.wordpress.com/
Link: "Constructing Scientific Communities Project" = https://conscicom.web.ox.ac.uk/

Retirement Page Image:
![sciencegossip_img](https://panoptes-uploads.zooniverse.org/production/project_avatar/7647ea52-d175-4920-b8e2-1ba595017918.jpeg)

Current Site: https://www.sciencegossip.org/

**Comment by eatyourgreens** [comment]
Can you also include a link to http://explore.sciencegossip.org/groups where you can browse or download the results?

For a random image from the results, there's also http://explore.sciencegossip.org/random

**Comment by adammcmaster** [comment]
If we're going to link to those then we need a plan for maintaining them/patching dependencies (and if we can't maintain them they will need to be shut down).

**Comment by eatyourgreens** [comment]
>If we're going to link to those then we need a plan for maintaining them/patching dependencies (and if we can't maintain them they will need to be shut down).

ConSciCom are paying us to rebuild http://explore.sciencegossip.org. Due probably early in the New Year.
