### ISSUE TITLE
Archive page for whaling.oldweather.org

### ISSUE THREAD

**Issue by trouille** [zooniverse/retirement#8]
Just copying here the thread from Slack, so it's easy to retrieve and Zach, Adam, Sarah can discuss as needed. 

Laura:
whaling.oldweather.org is officially no longer active, as of last week. They finished the last data set and now volunteers are only working through the spreadsheet effort (via links within oldweather.org).

Kevin’s request was that we move whaling.oldweather.org to x.oldweather.org for a couple months, if possible, while he goes through all the materials and moves over remaining stuff to his archives, etc.

But no active classifying, etc. is happening at whaling.oldweather.org (not sure if that helps you at all).

(Apparently moving to x.oldweather.org is something [Adam?] did for classic.oldweather.org previously, so they could do the same look-through of materials before fully retiring it, but also make sure that no volunteers went to the old URL (e.g. whaling.oldweather.org) and wasted time trying to do anything there.

Adam asked:
What do we want to put up in its place? Just the normal retirement page (similar to https://whale.fm)?

Laura responded:
Yes, thank you for thinking of that. A retirement/archived page along those lines would be good. Would it be helpful if I provide you copy for that?

Adam:
That'd be great, thanks. I was thinking this might be a good thing for @zach to do if he has time since it involves touching a couple of different parts of the infrastructure (DNS and Nginx config)

Zach:
:+1:

Zach:
link me at an issue with the details and I’ll put it on my ops list

Adam:
I'd be happy to pair on it next week too if you'd like

Zach:
Sure, keep in mind that I’ll be in Oxford the week of the 8th too, if it can wait.

**Comment by adammcmaster** [comment]
I'm not sure we want those Google docs links to be public since they allow anonymous editing, so I've removed them. I've also transferred the issue to the retirement repo, which contains the template for the new page.

**Comment by trouille** [comment]
Switching this from @mcbouslog to @wgranger , since Will is having the fun of creating a static page for the registration info, seems good timing to also have you create a static page for this archive whaling site (note: you don't need to do that this week, just in the next couple weeks).

**Comment by wgranger** [comment]
Ok. I think I understand what's going on here. Am I basically using the "template" folder as the boilerplate to set up a new folder on this repo for the retired whaling.oldweather site using content from the doc? I can open a PR when that's done, and I guess when it's merged @zwolf will take care of the setting up all the infrastructure things to make it live?

**Comment by wgranger** [comment]
@trouille What should this page say at the bottom? Take a look at "about this project," "similar project," and "data description" on whale.fm

**Comment by trouille** [comment]
see the Google doc at the bottom:
(Note: don’t add the sections below from whaleFM page like ‘About this Project’, etc. - not needed/links would likely get deprecated).

**Comment by wgranger** [comment]
Reopening as we still need some backend changes for this to be live. @adammcmaster @zwolf The frontend changes for Old Weather: Whaling were added to this repo, so this should be ready.

**Comment by adammcmaster** [comment]
This is deployed now.
